//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFM2B_GROUP_PROJECT.InvictusService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUser", Namespace="http://schemas.datacontract.org/2004/07/InvictusService")]
    [System.SerializableAttribute()]
    public partial class SystemUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IFM2B_GROUP_PROJECT.InvictusService.UserAddress[] UserAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserForgotCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UserForgotCodeSentTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IFM2B_GROUP_PROJECT.InvictusService.UserPayment[] UserPaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IFM2B_GROUP_PROJECT.InvictusService.UserAddress[] UserAddresses {
            get {
                return this.UserAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAddressesField, value) != true)) {
                    this.UserAddressesField = value;
                    this.RaisePropertyChanged("UserAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserForgotCode {
            get {
                return this.UserForgotCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserForgotCodeField, value) != true)) {
                    this.UserForgotCodeField = value;
                    this.RaisePropertyChanged("UserForgotCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UserForgotCodeSentTime {
            get {
                return this.UserForgotCodeSentTimeField;
            }
            set {
                if ((this.UserForgotCodeSentTimeField.Equals(value) != true)) {
                    this.UserForgotCodeSentTimeField = value;
                    this.RaisePropertyChanged("UserForgotCodeSentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserIPAddress {
            get {
                return this.UserIPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIPAddressField, value) != true)) {
                    this.UserIPAddressField = value;
                    this.RaisePropertyChanged("UserIPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IFM2B_GROUP_PROJECT.InvictusService.UserPayment[] UserPayments {
            get {
                return this.UserPaymentsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPaymentsField, value) != true)) {
                    this.UserPaymentsField = value;
                    this.RaisePropertyChanged("UserPayments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserStatus {
            get {
                return this.UserStatusField;
            }
            set {
                if ((this.UserStatusField.Equals(value) != true)) {
                    this.UserStatusField = value;
                    this.RaisePropertyChanged("UserStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSurname {
            get {
                return this.UserSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSurnameField, value) != true)) {
                    this.UserSurnameField = value;
                    this.RaisePropertyChanged("UserSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAddress", Namespace="http://schemas.datacontract.org/2004/07/InvictusService")]
    [System.SerializableAttribute()]
    public partial class UserAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IFM2B_GROUP_PROJECT.InvictusService.SystemUser SystemUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCountry {
            get {
                return this.AddressCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressCountryField, value) != true)) {
                    this.AddressCountryField = value;
                    this.RaisePropertyChanged("AddressCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressName {
            get {
                return this.AddressNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNameField, value) != true)) {
                    this.AddressNameField = value;
                    this.RaisePropertyChanged("AddressName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressPhoneNumber {
            get {
                return this.AddressPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressPhoneNumberField, value) != true)) {
                    this.AddressPhoneNumberField = value;
                    this.RaisePropertyChanged("AddressPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressPostalCode {
            get {
                return this.AddressPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressPostalCodeField, value) != true)) {
                    this.AddressPostalCodeField = value;
                    this.RaisePropertyChanged("AddressPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdressCity {
            get {
                return this.AdressCityField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressCityField, value) != true)) {
                    this.AdressCityField = value;
                    this.RaisePropertyChanged("AdressCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IFM2B_GROUP_PROJECT.InvictusService.SystemUser SystemUser {
            get {
                return this.SystemUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemUserField, value) != true)) {
                    this.SystemUserField = value;
                    this.RaisePropertyChanged("SystemUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPayment", Namespace="http://schemas.datacontract.org/2004/07/InvictusService")]
    [System.SerializableAttribute()]
    public partial class UserPayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Accounyt_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Expiry_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Payment_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IFM2B_GROUP_PROJECT.InvictusService.SystemUser SystemUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accounyt_No {
            get {
                return this.Accounyt_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.Accounyt_NoField, value) != true)) {
                    this.Accounyt_NoField = value;
                    this.RaisePropertyChanged("Accounyt_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expiry_Date {
            get {
                return this.Expiry_DateField;
            }
            set {
                if ((object.ReferenceEquals(this.Expiry_DateField, value) != true)) {
                    this.Expiry_DateField = value;
                    this.RaisePropertyChanged("Expiry_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payment_Type {
            get {
                return this.Payment_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Payment_TypeField, value) != true)) {
                    this.Payment_TypeField = value;
                    this.RaisePropertyChanged("Payment_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provider {
            get {
                return this.ProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderField, value) != true)) {
                    this.ProviderField = value;
                    this.RaisePropertyChanged("Provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IFM2B_GROUP_PROJECT.InvictusService.SystemUser SystemUser {
            get {
                return this.SystemUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemUserField, value) != true)) {
                    this.SystemUserField = value;
                    this.RaisePropertyChanged("SystemUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/InvictusService")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DISC_ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DISC_DiscPercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Extra_Image1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Extra_Image2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Extra_Image3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prod_DesciptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Prod_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prod_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prod_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Prod_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Prod_QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DISC_Active {
            get {
                return this.DISC_ActiveField;
            }
            set {
                if ((this.DISC_ActiveField.Equals(value) != true)) {
                    this.DISC_ActiveField = value;
                    this.RaisePropertyChanged("DISC_Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DISC_DiscPercent {
            get {
                return this.DISC_DiscPercentField;
            }
            set {
                if ((this.DISC_DiscPercentField.Equals(value) != true)) {
                    this.DISC_DiscPercentField = value;
                    this.RaisePropertyChanged("DISC_DiscPercent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extra_Image1 {
            get {
                return this.Extra_Image1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Extra_Image1Field, value) != true)) {
                    this.Extra_Image1Field = value;
                    this.RaisePropertyChanged("Extra_Image1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extra_Image2 {
            get {
                return this.Extra_Image2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Extra_Image2Field, value) != true)) {
                    this.Extra_Image2Field = value;
                    this.RaisePropertyChanged("Extra_Image2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extra_Image3 {
            get {
                return this.Extra_Image3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Extra_Image3Field, value) != true)) {
                    this.Extra_Image3Field = value;
                    this.RaisePropertyChanged("Extra_Image3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prod_Desciption {
            get {
                return this.Prod_DesciptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Prod_DesciptionField, value) != true)) {
                    this.Prod_DesciptionField = value;
                    this.RaisePropertyChanged("Prod_Desciption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prod_ID {
            get {
                return this.Prod_IDField;
            }
            set {
                if ((this.Prod_IDField.Equals(value) != true)) {
                    this.Prod_IDField = value;
                    this.RaisePropertyChanged("Prod_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prod_Image {
            get {
                return this.Prod_ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.Prod_ImageField, value) != true)) {
                    this.Prod_ImageField = value;
                    this.RaisePropertyChanged("Prod_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prod_Name {
            get {
                return this.Prod_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Prod_NameField, value) != true)) {
                    this.Prod_NameField = value;
                    this.RaisePropertyChanged("Prod_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prod_Price {
            get {
                return this.Prod_PriceField;
            }
            set {
                if ((this.Prod_PriceField.Equals(value) != true)) {
                    this.Prod_PriceField = value;
                    this.RaisePropertyChanged("Prod_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prod_Quantity {
            get {
                return this.Prod_QuantityField;
            }
            set {
                if ((this.Prod_QuantityField.Equals(value) != true)) {
                    this.Prod_QuantityField = value;
                    this.RaisePropertyChanged("Prod_Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvictusService.IInvictusService")]
    public interface IInvictusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/Register", ReplyAction="http://tempuri.org/IInvictusService/RegisterResponse")]
        int Register(string Name, string Surname, string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/Register", ReplyAction="http://tempuri.org/IInvictusService/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(string Name, string Surname, string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/getUser", ReplyAction="http://tempuri.org/IInvictusService/getUserResponse")]
        IFM2B_GROUP_PROJECT.InvictusService.SystemUser[] getUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/getUser", ReplyAction="http://tempuri.org/IInvictusService/getUserResponse")]
        System.Threading.Tasks.Task<IFM2B_GROUP_PROJECT.InvictusService.SystemUser[]> getUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/UpdateUser", ReplyAction="http://tempuri.org/IInvictusService/UpdateUserResponse")]
        bool UpdateUser(IFM2B_GROUP_PROJECT.InvictusService.SystemUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/UpdateUser", ReplyAction="http://tempuri.org/IInvictusService/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(IFM2B_GROUP_PROJECT.InvictusService.SystemUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/DeleteUser", ReplyAction="http://tempuri.org/IInvictusService/DeleteUserResponse")]
        bool DeleteUser(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/DeleteUser", ReplyAction="http://tempuri.org/IInvictusService/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/UpdateProduct", ReplyAction="http://tempuri.org/IInvictusService/UpdateProductResponse")]
        bool UpdateProduct(IFM2B_GROUP_PROJECT.InvictusService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/UpdateProduct", ReplyAction="http://tempuri.org/IInvictusService/UpdateProductResponse")]
        System.Threading.Tasks.Task<bool> UpdateProductAsync(IFM2B_GROUP_PROJECT.InvictusService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/GetAllProducts", ReplyAction="http://tempuri.org/IInvictusService/GetAllProductsResponse")]
        IFM2B_GROUP_PROJECT.InvictusService.Product[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/GetAllProducts", ReplyAction="http://tempuri.org/IInvictusService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<IFM2B_GROUP_PROJECT.InvictusService.Product[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/GetProduct", ReplyAction="http://tempuri.org/IInvictusService/GetProductResponse")]
        IFM2B_GROUP_PROJECT.InvictusService.Product GetProduct(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/GetProduct", ReplyAction="http://tempuri.org/IInvictusService/GetProductResponse")]
        System.Threading.Tasks.Task<IFM2B_GROUP_PROJECT.InvictusService.Product> GetProductAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/Login", ReplyAction="http://tempuri.org/IInvictusService/LoginResponse")]
        int Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvictusService/Login", ReplyAction="http://tempuri.org/IInvictusService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvictusServiceChannel : IFM2B_GROUP_PROJECT.InvictusService.IInvictusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvictusServiceClient : System.ServiceModel.ClientBase<IFM2B_GROUP_PROJECT.InvictusService.IInvictusService>, IFM2B_GROUP_PROJECT.InvictusService.IInvictusService {
        
        public InvictusServiceClient() {
        }
        
        public InvictusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvictusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvictusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvictusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Register(string Name, string Surname, string Email, string Password) {
            return base.Channel.Register(Name, Surname, Email, Password);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(string Name, string Surname, string Email, string Password) {
            return base.Channel.RegisterAsync(Name, Surname, Email, Password);
        }
        
        public IFM2B_GROUP_PROJECT.InvictusService.SystemUser[] getUser(int userId) {
            return base.Channel.getUser(userId);
        }
        
        public System.Threading.Tasks.Task<IFM2B_GROUP_PROJECT.InvictusService.SystemUser[]> getUserAsync(int userId) {
            return base.Channel.getUserAsync(userId);
        }
        
        public bool UpdateUser(IFM2B_GROUP_PROJECT.InvictusService.SystemUser user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(IFM2B_GROUP_PROJECT.InvictusService.SystemUser user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public bool DeleteUser(int ID) {
            return base.Channel.DeleteUser(ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(int ID) {
            return base.Channel.DeleteUserAsync(ID);
        }
        
        public bool UpdateProduct(IFM2B_GROUP_PROJECT.InvictusService.Product product) {
            return base.Channel.UpdateProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProductAsync(IFM2B_GROUP_PROJECT.InvictusService.Product product) {
            return base.Channel.UpdateProductAsync(product);
        }
        
        public IFM2B_GROUP_PROJECT.InvictusService.Product[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<IFM2B_GROUP_PROJECT.InvictusService.Product[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public IFM2B_GROUP_PROJECT.InvictusService.Product GetProduct(int ID) {
            return base.Channel.GetProduct(ID);
        }
        
        public System.Threading.Tasks.Task<IFM2B_GROUP_PROJECT.InvictusService.Product> GetProductAsync(int ID) {
            return base.Channel.GetProductAsync(ID);
        }
        
        public int Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
    }
}
